name: simple_lru_cache
version: 0.1.0
description: A simple Least Recently Used (LRU) cache implementation in Dart.
homepage: https://arkaung.github.io/dart_lru
repository: https://github.com/arkaung/dart_lru

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
